/* Problem: Write a method "makeArray" which generates an array of length "n" of random integer numbers
in the range 1 to 10.
Write and test a method called "addArray" which add two arrays of the same lenght generated by "makeArray".
Rewrite and test "makeAray" so that the range can be chosen between two integers N1 and N2.

*/

import java.util.Scanner;



public class part3{
	static Scanner input= new Scanner(System.in); 
	
	public static void main(String[] args){
		System.out.print("Enter an integer to generate an array: ");
		int d = input.nextInt();
		int []array= new int [d];
		makeArray(array);
		showArray(array);
		
		System.out.println("Enter a number to add two arrays: ");
		d = input.nextInt();
		int[] array1=new int [d];
		int[] array2=new int [d];
		int[] intArray=new int [2*d];
		
		makeArray(array1);
		showArray(array1);
		makeArray(array2);
		showArray(array2);
			
		addArray(array1, array2, intArray);
		showArray(intArray);
		
		System.out.println("Enter 3 numbers, n(the array size), N1 and N2 to generate an array: ");
		d = input.nextInt();
		int N1= input.nextInt();
		int N2= input.nextInt();
		
		int [] intArray2=new int [d];
		makeArray(intArray2, N1 ,N2);
		showArray(intArray2);
		
	}
	
	static void makeArray (int []_array){
		int n=_array.length;
		for(int i=0; i<n; i++){
			_array[i]=(int) (Math.random()*10);
		}
	}
	
	static void showArray(int []_array){
		int n=_array.length;
		System.out.print("[ ");
		for(int i=0; i<n; i++){
			System.out.print(_array[i]+"  ");
		}
		System.out.println("]");
	}
	
	static void addArray(int []array1, int []array2, int[]arrayResult){
		int n=array1.length;		
		int i;
		for(i=0; i<n;i++){
			arrayResult[i]=array1[i];
		}
		for(i=n; i<2*n;i++){
			arrayResult[i]=array2[i-n];
		}
	}
	
	static void makeArray (int []_array, int N1, int N2){
		int n=_array.length;		
		if(N1>N2){
		for(int i=0; i<n; i++){
			_array[i]=(int) ((Math.random()*(N1-N2))+N2);
			}
		}
		if(N2>N1){
			for(int i=0; i<n; i++){
			_array[i]=(int) ((Math.random()*(N2-N1))+N1);
			}
		}
	}
	
} 
